---
- hosts: all
  roles:
    - common
    - docker
    - etcd
    - openresty
    - supervisor

- hosts: dcloud1
  vars:
    letsencrypt:
      - registry1.dcloud.run
    registry:
      name: registry1
      domain: registry1.dcloud.run
  roles:
    - deploying
    - letsencrypt
    - registry
