filebeat.prospectors:
- input_type: log
  paths:
    - /var/lib/docker/containers/*/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

output.elasticsearch:
  hosts: ["{{elasticsearch}}"]
  protocol: "http"
