version: 2

jobs:
  build:
    working_directory: /go/src/github.com/jysperm/deploybeta

    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: go mod tidy
      - run: go build -v
