version: 2

jobs:
  build:
    working_directory: /go/src/github.com/jysperm/deploying

    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - run: go build -v
