---
- name: setup hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: setup iptables allow ports
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination: '{{ansible_host}}'
    destination_port: '{{ item }}'
    jump: ACCEPT
  with_items:
    - 22
    - 80
    - 443

- name: setup iptables policy
  iptables:
    table: filter
    chain: INPUT
    policy: DROP

- name: install apt packages
  apt:
    name: '{{ item }}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - htop
    - software-properties-common
    - vim

- name: ensures directory exists
  file:
    path: '/root/downloads'
    state: 'directory'
