---
- name: setup hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: install apt packages
  apt: name={{item}}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - htop
    - software-properties-common
    - vim

- name: ensures directory exists
  file:
    path: '/root/downloads'
    state: 'directory'
