- name: create deploying user
  user:
    name: 'deploying'

- name: upload binaries
  unarchive:
    src: '../releases/deploying-linux-amd64.tar.gz'
    dest: '/home/deploying'
    owner: 'deploying'
  notify:
    - restart deploying

- name: upload supervisor configuration
  template:
    src: 'supervisor.conf'
    dest: '/etc/supervisor/conf.d/deploying.conf'
  notify:
    - restart supervisor

- name: upload nginx configuration
  template:
    src: 'nginx.conf'
    dest: '/etc/nginx/sites-enabled/deploying.conf'
  notify:
    - restart openresty
