---
- name: restart openresty
  service:
    name: 'openresty'
    state: restarted

- name: restart supervisor
  service:
    name: 'supervisor'
    state: restarted

- name: restart deploybeta
  supervisorctl:
    name: 'deploybeta'
    state: restarted
