---
- name: add apt repository key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- name: add apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable'
    update_cache: yes

- name: install apt packages
  apt: name=docker-ce
